services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    ports:
    - "3306:3306"
    volumes:
    - ./db-persist:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_web_server
  #   volumes:
  #     - ./fe:/usr/share/nginx/html:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./be
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./be/app.py:/app/app.py
  #   command: python app.py
  #   devices:
  #     - "/dev/ttyACM0:/dev/ttyACM0" 
  #   depends_on:
  #     - db